import { createEmptyVaultPrefill, createVaultSuggestion, setVaultPrefill } from "./vaultCanonicalMap.js";

const ARCHETYPE_TO_PREFILL = Object.freeze({ UNI: ["archetypes.is_generalist"], DOE: ["archetypes.is_doer"], ORC: ["archetypes.is_orchestrator"], CRT: ["archetypes.is_creator"], RDR: ["archetypes.is_reader"], CMP: ["archetypes.conversational_ui"], TRN: ["archetypes.sens_bio"], JDG: ["archetypes.is_judge", "archetypes.is_judge_hr", "archetypes.is_judge_legal"], OPT: ["archetypes.is_optimizer", "archetypes.sens_fin"], SHD: ["archetypes.is_shield"], MOV: ["archetypes.is_mover"] });
const SURFACE_TO_PREFILL = Object.freeze({ PII: [["compliance.processes_pii", "yes"]], Financial: [["compliance.sens_fin", true]], Employment: [["compliance.sens_employment", true]], Minors: [["compliance.minors", true]] });
function asArray(value) { return Array.isArray(value) ? value : []; }
function asObject(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function report(stage9) { return stage9?.report?.report_data || stage9?.report_data || stage9; }
function target(stage9) { const data = report(stage9); return asObject(data.target_profile_v2 || stage9?.target_profile_v2 || stage9?.compiler_output?.target_profile_v2); }
function featureProfile(stage9) { const data = report(stage9); return asObject(data.feature_profile_v2 || stage9?.feature_profile_v2 || stage9?.compiler_output?.feature_profile_v2); }
function features(stage9) { return asArray(featureProfile(stage9).feature_inventory); }
function candidateValue(candidate) { const c = asObject(candidate); return c.status === "PREFILL_READY" && c.value !== undefined && c.value !== null && String(c.value).trim() !== "" ? c : null; }
function setIfPresent(prefill, path, value, basis, confidence, refs, warnings) { if (value === undefined || value === null || value === "") return false; if (Array.isArray(value) && !value.length) return false; return setVaultPrefill(prefill, path, createVaultSuggestion(value, basis, confidence, refs), warnings); }
function applyCandidate(prefill, path, candidate, warnings) { const c = candidateValue(candidate); if (!c) return; setIfPresent(prefill, path, c.value, c.basis || `Derived from canonical ${path} candidate.`, c.confidence || "high", c.evidence_refs || [], warnings); }
function deriveBaseline(stage9, prefill, warnings) { const t = target(stage9); const id = asObject(t.identity); const baseline = asObject(asObject(t.vault_baseline_candidates).baseline); applyCandidate(prefill, "baseline.company", baseline.company, warnings); applyCandidate(prefill, "baseline.entity_type", baseline.entity_type, warnings); applyCandidate(prefill, "baseline.address", baseline.address, warnings); applyCandidate(prefill, "baseline.legal_email", baseline.legal_email, warnings); applyCandidate(prefill, "baseline.privacy_email", baseline.privacy_email, warnings); applyCandidate(prefill, "baseline.products", baseline.products, warnings); applyCandidate(prefill, "baseline.jurisdiction.country", asObject(baseline.jurisdiction).country, warnings); applyCandidate(prefill, "baseline.jurisdiction.state", asObject(baseline.jurisdiction).state, warnings); applyCandidate(prefill, "baseline.market", baseline.market, warnings); applyCandidate(prefill, "baseline.delivery.app", asObject(baseline.delivery).app, warnings); applyCandidate(prefill, "baseline.delivery.api", asObject(baseline.delivery).api, warnings); applyCandidate(prefill, "baseline.revenue_model", baseline.revenue_model, warnings); applyCandidate(prefill, "baseline.has_beta", baseline.has_beta, warnings); const integrations = asObject(baseline.integrations); ["slack", "crm", "stripe", "github", "webhooks", "none"].forEach((key) => applyCandidate(prefill, `baseline.integrations.${key}`, integrations[key], warnings)); if (!prefill.baseline.company) setIfPresent(prefill, "baseline.company", id.legal_name || id.brand_name, "Derived from target_profile_v2.identity with legal_name priority.", "high", ["target_profile_v2.identity"], warnings); if (!prefill.baseline.products) { const names = [...new Set(features(stage9).map((f) => f.business_label_or_product_area || f.feature_name).filter(Boolean))]; setIfPresent(prefill, "baseline.products", names, "Derived from feature_profile_v2.feature_inventory business labels.", "medium", ["feature_profile_v2.feature_inventory"], warnings); } }
function deriveArchetypes(stage9, prefill, warnings) { const codes = new Set(); features(stage9).forEach((f) => asArray(f.archetype_codes).forEach((c) => codes.add(String(c).toUpperCase()))); codes.forEach((code) => (ARCHETYPE_TO_PREFILL[code] || []).forEach((path) => setIfPresent(prefill, path, true, `Derived from canonical Stage 5 archetype ${code}.`, "high", ["feature_profile_v2.feature_inventory"], warnings))); }
function deriveCompliance(stage9, prefill, warnings) { const tokens = new Set(); features(stage9).forEach((f) => asArray(f.surface_tokens).forEach((s) => tokens.add(String(s)))); asArray(featureProfile(stage9).regulated_surface_map).forEach((s) => tokens.add(String(s.surface_token || ""))); tokens.forEach((token) => (SURFACE_TO_PREFILL[token] || []).forEach(([path, value]) => setIfPresent(prefill, path, value, `Derived from canonical Stage 5 surface ${token}.`, "high", ["feature_profile_v2.regulated_surface_map"], warnings))); }
function deriveArchitecture(stage9, prefill, warnings) { asArray(featureProfile(stage9).architecture_hints).filter((h) => h.disposition === "prefill_candidate").forEach((hint) => { const refs = [hint.feature_id || "feature_profile_v2.architecture_hints"]; const basis = `Derived from explicit architecture_hints entry ${hint.hint_id || ""}.`; if (hint.hint_type === "memory") setIfPresent(prefill, "architecture.memory", hint.hint_value, basis, hint.confidence || "medium", refs, warnings); if (hint.hint_type === "cloud_host") setIfPresent(prefill, "architecture.cloud_host", hint.hint_value, basis, hint.confidence || "medium", refs, warnings); if (hint.hint_type === "vector_db") setIfPresent(prefill, "architecture.vector_db", hint.hint_value, basis, hint.confidence || "medium", refs, warnings); if (hint.hint_type === "model_provider" || hint.hint_type === "subprocessor") setIfPresent(prefill, "architecture.sub_processors.other", hint.hint_value, basis, hint.confidence || "medium", refs, warnings); }); }
export function deriveVaultPrefillFromStage9(stage9ReportData, warnings = []) { const prefill = createEmptyVaultPrefill(); deriveBaseline(stage9ReportData, prefill, warnings); deriveArchitecture(stage9ReportData, prefill, warnings); deriveArchetypes(stage9ReportData, prefill, warnings); deriveCompliance(stage9ReportData, prefill, warnings); return prefill; }
