const FINAL_STATUSES = new Set(["TRIGGERED", "CONTROLLED", "NOT_TRIGGERED", "NOT_APPLICABLE", "INSUFFICIENT_EVIDENCE"]);
const GATE_RESULTS = new Set(["PASS", "FAIL", "NOT_REQUIRED", "INSUFFICIENT"]);
const TRUE_BASIS_PREFIXES = ["TRUE_EVIDENCE:", "TRUE_ABSENCE:", "TRUE_FEATURE_MAP:", "TRUE_STAGE6_REVIEW:", "TRUE_STAGE6_LEGAL_UNIT:", "TRUE_STAGE6_DATA_FLOW:", "TRUE_INSUFFICIENT:"];
const FALSE_BASIS_PREFIXES = ["FALSE_NOT_SATISFIED:", "FALSE_NOT_APPLICABLE:", "FALSE_INSUFFICIENT:"];
const RUN_REASONS = new Set(["UNI_ALWAYS_RUN", "STAGE5_INT_TRIGGERED", "CONDITIONAL_DOC_REVIEW", "STAGE5_DEGRADED_FALLBACK"]);
const ALLOWED_GLOBAL_REFS = new Set(["GLOBAL", "MULTI", "UNKNOWN", "NO_STAGE5_TRIGGER"]);
const LEGACY_STAGE6_REVIEW_PREFIX = ["TRUE", "LEGAL", "STACK:"].join("_");
const RETIRED_STAGE6_REVIEW_KEY = ["legal", "stack", "review"].join("_");
const FORBIDDEN_KEYS = new Set(["source_bundle", "target_feature_profile", RETIRED_STAGE6_REVIEW_KEY, "operator_challenge_gate", "high_risk_checks", "reopened_rows", "findings", "controlled_rows", "insufficient_evidence_rows", "report_data", "vault_prefill_suggestions", "vault_confirmation_questions", "assembly_route", "technical_audit_log", "html", "registry_batch_evaluation"]);
const ID_KEY = ["thr", "eat_id"].join("");
const SRC_ID_KEY = ["Thr", "eat_ID"].join("");
const NAME_KEY = ["thr", "eat_name"].join("");
const SRC_NAME_KEY = ["Thr", "eat_Name"].join("");

function push(errors, instancePath, message, params = {}) { errors.push({ keyword: "registry_ledger_guardrail", instancePath, schemaPath: "#/registryLedgerGuardrails", message, params }); }
function warn(warnings, instancePath, message, params = {}) { warnings.push({ keyword: "registry_ledger_guidance", instancePath, schemaPath: "#/registryLedgerGuidance", message, params }); }
function rep(repairs, instancePath, action, params = {}) { repairs.push({ keyword: "registry_ledger_repair", severity: "REPAIRABLE", instancePath, schemaPath: "#/registryLedgerRepairs", action, params }); }
function nonEmpty(value) { return typeof value === "string" && value.trim().length > 0; }
function rowId(row, index) { return String(row?.[SRC_ID_KEY] || row?.[ID_KEY] || `MISSING_ROW_${index + 1}`).trim(); }
function rowName(row) { return String(row?.[SRC_NAME_KEY] || row?.[NAME_KEY] || row?.name || "").trim(); }
function entryId(entry) { return String(entry?.[ID_KEY] || entry?.[SRC_ID_KEY] || "").trim(); }
function rowArchetype(row) { return String(row?.[SRC_ID_KEY] || row?.[ID_KEY] || "").split("_")[0] || String(row?.Archetype || row?.archetype?.code || row?.archetype || "").trim(); }
function asBool(value) { if (typeof value === "boolean") return value; const s = String(value ?? "").trim().toLowerCase(); if (["true", "yes", "y", "1"].includes(s)) return true; if (["false", "no", "n", "0"].includes(s)) return false; return null; }
function featureIds(input = {}) { const profile = input?.target_feature_profile || input?.feature_profile_v2 || {}; const fromProfile = (profile?.feature_inventory || []).map((feature) => feature?.feature_id).filter(Boolean); const nav = input?.stage6_to_stage7_adapter?.stage7_navigation_index || input?.stage6_review?.stage7_navigation_index || {}; const fromStage6 = [...(nav.feature_to_data_flow_index || []).map((row) => row?.feature_id), ...(nav.feature_to_legal_unit_index || []).map((row) => row?.feature_id)].filter(Boolean); return new Set([...fromProfile, ...fromStage6]); }
function hasTargetProfile(input = {}) { return Boolean(input?.target_profile || input?.target_profile_v2 || input?.company_profile); }
function targetProfileFor(input = {}) { return input?.target_profile || input?.target_profile_v2 || input?.company_profile || {}; }
function hasJurisdictionSignal(profile = {}) { const j = profile?.jurisdiction || {}; return Boolean(j.registered_or_notice_country || j.governing_law_country || j.headquarters || j.operating_markets?.length || j.data_sovereignty_signature); }
function walk(value, errors, path = "") { if (!value || typeof value !== "object") return; if (Array.isArray(value)) return value.forEach((item, index) => walk(item, errors, `${path}/${index}`)); for (const [key, child] of Object.entries(value)) { const childPath = `${path}/${key}`; if (FORBIDDEN_KEYS.has(key)) push(errors, childPath, `forbidden key emitted: ${key}`, { key }); walk(child, errors, childPath); } }
function normalizeGate(value) { const raw = String(value ?? "").trim().toUpperCase().replace(/[\s-]+/g, "_"); if (GATE_RESULTS.has(raw)) return raw; if (["TRUE", "YES", "MATCH", "MATCHED", "APPLICABLE", "PASS_WITH_WARNINGS"].includes(raw)) return "PASS"; if (["FALSE", "NO", "MISMATCH", "NOT_APPLICABLE", "N_A", "NA", "NONE"].includes(raw)) return "NOT_REQUIRED"; if (["UNKNOWN", "UNCLEAR", "INSUFFICIENT_EVIDENCE"].includes(raw)) return "INSUFFICIENT"; return null; }
function normalizeStatus(value) { const raw = String(value ?? "").trim().toUpperCase().replace(/[\s-]+/g, "_"); if (FINAL_STATUSES.has(raw)) return raw; if (["ACTIVE", "TRIGGER", "TRIGGERED_TRUE"].includes(raw)) return "TRIGGERED"; if (["CONTROL", "CONTROLLED_TRUE", "MITIGATED"].includes(raw)) return "CONTROLLED"; if (["FALSE", "NO_TRIGGER", "NOT_TRIGGERED_FALSE"].includes(raw)) return "NOT_TRIGGERED"; if (["N_A", "NA", "NOT_APPLICABLE_ARCHETYPE", "NOT_APPLICABLE_SURFACE"].includes(raw)) return "NOT_APPLICABLE"; if (["UNKNOWN", "UNCLEAR", "INSUFFICIENT", "INSUFFICIENT_INFORMATION"].includes(raw)) return "INSUFFICIENT_EVIDENCE"; return null; }
function routeMap(input = {}) { const map = new Map(); for (const item of input?.stage7_route_contract?.route_records || []) if (item?.threat_id) map.set(String(item.threat_id), item); for (const [index, row] of (input.registry_rows || []).entries()) { const id = rowId(row, index); const route = row?.stage7_route_contract || row?._stage7_route; if (route) map.set(id, route); else map.set(id, { threat_id: id, route_reason: rowArchetype(row) === "UNI" ? "UNI_ALWAYS_RUN" : "STAGE5_INT_TRIGGERED", route: "RUN" }); } return map; }
function coverageMap(input = {}) { const map = new Map(); for (const item of input?.stage7_evidence_coverage_manifest || input?.stage7_evidence_safety?.coverage_manifest || []) if (item?.threat_id) map.set(String(item.threat_id), item); return map; }
function isRunRoute(route = {}) { return RUN_REASONS.has(String(route.route_reason || "").toUpperCase()) || route.route === "RUN"; }
function expectedStatus(entry, route = {}) { if (!isRunRoute(route)) return "NOT_APPLICABLE"; if (entry.final_status === "INSUFFICIENT_EVIDENCE") return "INSUFFICIENT_EVIDENCE"; if (entry.trigger_if_result === true && entry.exclude_if_result === true) return "CONTROLLED"; if (entry.trigger_if_result === true && entry.exclude_if_result === false) return "TRIGGERED"; if (entry.trigger_if_result === false) return "NOT_TRIGGERED"; return "INSUFFICIENT_EVIDENCE"; }
function normalizeBasis(condition, path, errors, warnings, repairs) { if (!nonEmpty(condition.basis)) { condition.basis = condition.result === false ? "FALSE_INSUFFICIENT: evidence basis not pinpointed." : "TRUE_INSUFFICIENT: evidence basis not pinpointed."; rep(repairs, path, "fill_condition_basis_fallback"); warn(warnings, path, "condition.basis was empty; filled diagnostic fallback"); } if (String(condition.basis).startsWith(LEGACY_STAGE6_REVIEW_PREFIX)) { condition.basis = String(condition.basis).replace(new RegExp(`^${LEGACY_STAGE6_REVIEW_PREFIX}\\s*`), "TRUE_STAGE6_REVIEW: "); rep(repairs, path, "repair_legacy_stage6_basis_prefix"); } const before = String(condition.basis || ""); if (condition.result === false && /^TRUE_[A-Z0-9_]+\s*:/i.test(before)) { condition.basis = before.replace(/^TRUE_[A-Z0-9_]+\s*:/i, "FALSE_NOT_SATISFIED:"); rep(repairs, path, "repair_condition_basis_direction_to_false"); } if (condition.result === true && /^FALSE_[A-Z0-9_]+\s*:/i.test(before)) { condition.basis = before.replace(/^FALSE_[A-Z0-9_]+\s*:/i, "TRUE_EVIDENCE:"); rep(repairs, path, "repair_condition_basis_direction_to_true"); } const basis = String(condition.basis || ""); const canonical = condition.result ? TRUE_BASIS_PREFIXES.some((p) => basis.startsWith(p)) : FALSE_BASIS_PREFIXES.some((p) => basis.startsWith(p)); const directional = condition.result ? /^TRUE_[A-Z0-9_]+\s*:/i.test(basis) : /^FALSE_[A-Z0-9_]+\s*:/i.test(basis); if (!canonical && directional) warn(warnings, path, "noncanonical diagnostic prefix passed because TRUE/FALSE direction matches result", { basis }); if (!canonical && !directional) push(errors, path, "condition.basis must start with TRUE_/FALSE_ diagnostic prefix", { basis }); }
function normalizeTop(output, repairs, warnings) { for (const key of Object.keys(output)) if (!["batch_warnings", "registry_batch_meta", "registry_evaluation_ledger"].includes(key)) { delete output[key]; rep(repairs, `/${key}`, "strip_extra_top_level_key", { key }); warn(warnings, `/${key}`, "extra top-level key stripped", { key }); } if (!Array.isArray(output.batch_warnings)) { output.batch_warnings = output.batch_warnings == null ? [] : [String(output.batch_warnings)]; rep(repairs, "/batch_warnings", "normalize_batch_warnings_to_array"); } output.batch_warnings = output.batch_warnings.map((x) => typeof x === "string" ? x : JSON.stringify(x)); }
function entryFlagsPacketInsufficiency(entry = {}) { return /EVIDENCE_PACKET_INSUFFICIENT|PACKET_INSUFFICIENT|MISSING_REQUIRED_EVIDENCE_CLASS/i.test(`${entry.evidence_ref || ""} ${entry.reasoning_summary || ""} ${entry.authority_relevance || ""}`); }

export function validateRegistryLedgerGuardrails(output, { input = {} } = {}) {
  const errors = [], warnings = [], repairs = [], routes = routeMap(input), coverage = coverageMap(input);
  if (!output || typeof output !== "object" || Array.isArray(output)) { push(errors, "", "registry ledger output must be an object"); return { ok: false, errors, warnings, repairs }; }
  normalizeTop(output, repairs, warnings); walk(output, errors, "");
  const rows = Array.isArray(input?.registry_rows) ? input.registry_rows : [];
  const ledger = Array.isArray(output.registry_evaluation_ledger) ? output.registry_evaluation_ledger : [];
  const meta = output.registry_batch_meta || {};
  const allowedFeatureIds = featureIds(input);
  if (!hasTargetProfile(input)) push(errors, "/target_profile", "Stage 7 input must include canonical target_profile from Stage 4."); else if (!hasJurisdictionSignal(targetProfileFor(input))) warn(warnings, "/target_profile/jurisdiction", "target_profile jurisdiction signal is thin or unknown; passed as warning.");
  for (const key of ["batch_warnings", "registry_batch_meta", "registry_evaluation_ledger"]) if (!Object.prototype.hasOwnProperty.call(output, key)) push(errors, `/${key}`, `missing required top-level key: ${key}`);
  if (meta.registry_count_loaded !== rows.length) push(errors, "/registry_batch_meta/registry_count_loaded", "registry_count_loaded must equal supplied row count", { expected: rows.length, actual: meta.registry_count_loaded });
  if (ledger.length !== rows.length) push(errors, "/registry_evaluation_ledger", "ledger length must equal supplied row count", { expected: rows.length, actual: ledger.length });
  ledger.forEach((entry, index) => {
    const base = `/registry_evaluation_ledger/${index}`, row = rows[index] || {}, expectedId = rowId(row, index), route = routes.get(expectedId) || {}, coverageRow = coverage.get(expectedId) || {};
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) { push(errors, base, "ledger entry must be an object"); return; }
    if (entry.entry_number !== index + 1) { entry.entry_number = index + 1; rep(repairs, `${base}/entry_number`, "repair_entry_number"); }
    if (entryId(entry) !== expectedId) push(errors, `${base}/${ID_KEY}`, "row id must preserve supplied registry row id", { expected: expectedId, actual: entryId(entry) });
    if (!nonEmpty(entry[NAME_KEY])) { entry[NAME_KEY] = rowName(row) || expectedId; rep(repairs, `${base}/${NAME_KEY}`, "fill_name_from_registry_row"); }
    for (const key of ["archetype_gate", "surface_gate"]) { const gate = normalizeGate(entry[key]); if (gate) { if (entry[key] !== gate) rep(repairs, `${base}/${key}`, `normalize_${key}`, { from: entry[key], to: gate }); entry[key] = gate; } else { entry[key] = "INSUFFICIENT"; rep(repairs, `${base}/${key}`, `fallback_${key}_to_insufficient`); warn(warnings, `${base}/${key}`, `${key} normalized to INSUFFICIENT`); } }
    if (!nonEmpty(entry.authority_relevance)) { entry.authority_relevance = "Authority relevance not pinpointed from available evidence; passed as warning."; rep(repairs, `${base}/authority_relevance`, "fill_authority_relevance_fallback"); warn(warnings, `${base}/authority_relevance`, "authority_relevance missing; filled fallback"); }
    if (!Array.isArray(entry.conditions)) { entry.conditions = []; rep(repairs, `${base}/conditions`, "normalize_missing_conditions_to_empty_array"); }
    if (isRunRoute(route) && entry.conditions.length === 0) { rep(repairs, base, "row_reinvestigation_required", { threat_id: expectedId, reason: "applicable row has no condition-level investigation" }); warn(warnings, base, "applicable row lacks condition-level investigation; should be reinvestigated row-by-row if runtime supports reinvestigation", { threat_id: expectedId }); }
    entry.conditions.forEach((condition, cIndex) => { const cBase = `${base}/conditions/${cIndex}`; if (!condition || typeof condition !== "object" || Array.isArray(condition)) { push(errors, cBase, "condition must be an object"); return; } if (!nonEmpty(condition.condition_id)) { condition.condition_id = `condition_${cIndex + 1}`; rep(repairs, `${cBase}/condition_id`, "fill_missing_condition_id"); } const result = asBool(condition.result); if (typeof condition.result !== "boolean" && result !== null) { condition.result = result; rep(repairs, `${cBase}/result`, "normalize_condition_result_boolean"); } if (typeof condition.result !== "boolean") push(errors, `${cBase}/result`, "condition.result must be boolean"); else normalizeBasis(condition, `${cBase}/basis`, errors, warnings, repairs); });
    for (const key of ["trigger_if_result", "exclude_if_result"]) { const bool = asBool(entry[key]); if (typeof entry[key] !== "boolean" && bool !== null) { entry[key] = bool; rep(repairs, `${base}/${key}`, `normalize_${key}_boolean`); } if (typeof entry[key] !== "boolean") push(errors, `${base}/${key}`, `${key} must be boolean`); }
    const status = normalizeStatus(entry.final_status); if (status) { if (entry.final_status !== status) rep(repairs, `${base}/final_status`, "normalize_final_status", { from: entry.final_status, to: status }); entry.final_status = status; } else push(errors, `${base}/final_status`, "final_status must use closed status vocabulary", { actual: entry.final_status });
    if (!Array.isArray(entry.feature_refs)) { entry.feature_refs = ["UNKNOWN"]; rep(repairs, `${base}/feature_refs`, "normalize_missing_feature_refs_to_unknown"); }
    entry.feature_refs = entry.feature_refs.map((ref, rIndex) => { if (allowedFeatureIds.has(ref) || ALLOWED_GLOBAL_REFS.has(ref)) return ref; const s = String(ref ?? "").trim().toUpperCase().replace(/[\s-]+/g, "_"); rep(repairs, `${base}/feature_refs/${rIndex}`, "normalize_unresolved_feature_ref", { from: ref }); if (!["N_A", "NA", "NONE", "NOT_APPLICABLE", "NO_STAGE5_TRIGGER", "UNKNOWN", ""].includes(s)) warn(warnings, `${base}/feature_refs/${rIndex}`, "feature_ref did not match known ids; normalized", { ref }); return s === "NO_STAGE5_TRIGGER" ? "NO_STAGE5_TRIGGER" : "UNKNOWN"; });
    if (!nonEmpty(entry.evidence_ref)) { entry.evidence_ref = "EVIDENCE_NOT_PINPOINTED"; rep(repairs, `${base}/evidence_ref`, "fill_evidence_ref_fallback"); warn(warnings, `${base}/evidence_ref`, "evidence_ref missing; filled fallback"); }
    if (!nonEmpty(entry.reasoning_summary)) { entry.reasoning_summary = "Reasoning summary not pinpointed; row retained for forensic continuity."; rep(repairs, `${base}/reasoning_summary`, "fill_reasoning_summary_fallback"); warn(warnings, `${base}/reasoning_summary`, "reasoning_summary missing; filled fallback"); }
    if (typeof entry.trigger_if_result === "boolean" && typeof entry.exclude_if_result === "boolean") { const wanted = expectedStatus(entry, route); if (entry.final_status !== wanted && FINAL_STATUSES.has(entry.final_status)) { rep(repairs, `${base}/final_status`, "repair_final_status_from_route_and_boolean_logic", { from: entry.final_status, to: wanted, route_reason: route.route_reason || null }); entry.final_status = wanted; } }
    if (isRunRoute(route) && entry.final_status === "NOT_APPLICABLE") { entry.final_status = "INSUFFICIENT_EVIDENCE"; rep(repairs, `${base}/final_status`, "repair_applicable_row_not_applicable_to_insufficient_evidence", { route_reason: route.route_reason || null }); warn(warnings, `${base}/final_status`, "Runtime-applicable row emitted NOT_APPLICABLE; repaired to INSUFFICIENT_EVIDENCE", { route_reason: route.route_reason || null }); }
    if (!isRunRoute(route) && entry.final_status !== "NOT_APPLICABLE") { entry.final_status = "NOT_APPLICABLE"; rep(repairs, `${base}/final_status`, "repair_skipped_row_to_not_applicable", { route_reason: route.route_reason || null }); }
    if (isRunRoute(route) && (coverageRow.expansion_required_before_final_unknown === true || entryFlagsPacketInsufficiency(entry))) { rep(repairs, base, "row_reinvestigation_required", { threat_id: expectedId, reason: "evidence_packet_incomplete_or_model_flagged_packet_insufficient", evidence_expansion_required: true, missing_required_evidence_classes: coverageRow.missing_required_evidence_classes || [] }); warn(warnings, base, "runtime-applicable row needs evidence expansion before final UNKNOWN/INSUFFICIENT_EVIDENCE is accepted", { threat_id: expectedId, missing_required_evidence_classes: coverageRow.missing_required_evidence_classes || [] }); }
    if (entry.final_status === "TRIGGERED" && !(entry.trigger_if_result === true && entry.exclude_if_result === false)) push(errors, `${base}/final_status`, "TRIGGERED requires trigger_if_result=true and exclude_if_result=false");
    if (entry.final_status === "CONTROLLED" && !(entry.trigger_if_result === true && entry.exclude_if_result === true)) push(errors, `${base}/final_status`, "CONTROLLED requires trigger_if_result=true and exclude_if_result=true");
    if (entry.final_status === "NOT_TRIGGERED" && entry.trigger_if_result !== false) push(errors, `${base}/final_status`, "NOT_TRIGGERED requires trigger_if_result=false");
  });
  return { ok: errors.length === 0, errors, warnings, repairs };
}
