import { TARGET_PROFILE_REVIEW_CONTRACT } from "./target-profile-review.contract.js";
import { validateTargetProfileReviewOutput } from "./validators/target-profile-review.validator.js";
import { readPhaseRouteRuntimePacket } from "../02-cartography-index/services/phase-route-runtime.reader.js";

const LOCKED_STATUSES = new Set(["LOCKED", "LOCKED_WITH_LIMITATIONS"]);
const CONTROLLED_VALUES = new Set(TARGET_PROFILE_REVIEW_CONTRACT.output_contract.controlled_field_values);

export const TARGET_PROFILE_REVIEW_RUNNER_STATUS = Object.freeze({ phase_runner: "target-profile-review.runner", central_phase_id: TARGET_PROFILE_REVIEW_CONTRACT.central_phase_id, public_label: TARGET_PROFILE_REVIEW_CONTRACT.public_label, phase_owned_runner: true, production_entrypoint_switched: true, global_production_deployment_switched: false, root_validator_dependency_removed: true, phase2g_route_scoped_runtime_reader_active: true, direct_contract_read_loading_forbidden: true, profile_forensics_inputs_forbidden: true, writes: [...TARGET_PROFILE_REVIEW_CONTRACT.material_job.writes], routing_manifest_read: "phase_routing_manifest" });

export async function runTargetProfileReviewPhase({ run, internalJobId = "M7_TARGET_PROFILE", contract, readArtifacts, buildPrompt, callProvider, saveArtifact } = {}) {
  assertRuntimeContract(contract); assertCallback(readArtifacts, "readArtifacts"); assertCallback(buildPrompt, "buildPrompt"); assertCallback(callProvider, "callProvider"); assertCallback(saveArtifact, "saveArtifact");
  const routed = await readPhaseRouteRuntimePacket({ internalJobId, readArtifacts, consumerAgentId: contract.agent_id || contract.actor_id });
  const artifacts = routed.artifacts;
  assertRoutePacket(artifacts.phase_route_runtime_packet, internalJobId);
  const prompt = await buildPrompt({ prompt_files: contract.prompt_files, prompt_file: contract.prompt_file, phase: internalJobId, run, artifacts, writes: contract.writes, references: contract.references || [] });
  const providerResult = await callProvider({ prompt, phase: TARGET_PROFILE_REVIEW_CONTRACT.central_phase_id });
  const output = providerResult?.json || providerResult || {};
  validateTargetProfileReviewOutput(output, { phase: internalJobId });
  const phaseLockStatus = resolveTargetProfileReviewLockStatus(output.target_profile || output);
  const saved_artifacts = [];
  for (const artifactName of contract.writes) { const artifact = output?.[artifactName]; if (!artifact || typeof artifact !== "object" || Array.isArray(artifact)) throw new Error(`TARGET_PROFILE_REVIEW_OUTPUT_MISSING_ARTIFACT:${artifactName}`); await saveArtifact({ artifact_name: artifactName, artifact, lock_status: phaseLockStatus }); saved_artifacts.push(artifactName); }
  return { ok: true, output, artifacts_read: Object.keys(artifacts).sort(), saved_artifacts, phase_lock_status: phaseLockStatus, model_metadata: providerResult?.metadata || {}, legal_signal_derivation_profile_supplied_by_phase2g: Boolean(artifacts.legal_signal_derivation_profile), phase2g_route_id: routed.route.route_id, phase2g_bucket_id: routed.route.bucket_id, target_profile_review_phase_runner_used: true };
}
function assertRuntimeContract(contract = {}) { if (contract.central_phase_id !== TARGET_PROFILE_REVIEW_CONTRACT.central_phase_id) throw new Error(`TARGET_PROFILE_REVIEW_CONTRACT_MISMATCH:${contract.central_phase_id || "missing"}`); if (contract.public_label !== TARGET_PROFILE_REVIEW_CONTRACT.public_label) throw new Error(`TARGET_PROFILE_REVIEW_LABEL_MISMATCH:${contract.public_label || "missing"}`); if (!(contract.reads || []).includes("phase_routing_manifest")) throw new Error("TARGET_PROFILE_REVIEW_PHASE2G_MANIFEST_READ_MISSING"); assertSameArray(contract.writes || [], TARGET_PROFILE_REVIEW_CONTRACT.material_job.writes, "TARGET_PROFILE_REVIEW_WRITES"); if ((contract.references || []).includes("M7_TARGET_PROFILE_DERIVATION_AUTHORITY.yaml") !== true) throw new Error("TARGET_PROFILE_REVIEW_AUTHORITY_REFERENCE_MISSING"); }
function assertRoutePacket(packet = {}, internalJobId) { if (packet.routing_authority !== "P2G_CENTRALIZED_PHASE_ROUTING_AUTHORITY") throw new Error("TARGET_PROFILE_REVIEW_PHASE2G_AUTHORITY_MISSING"); if (packet.internal_job_id !== internalJobId) throw new Error(`TARGET_PROFILE_REVIEW_PHASE2G_JOB_MISMATCH:${packet.internal_job_id || "missing"}`); if (packet.lossless_evidence_role !== "PRIMARY_EVIDENCE") throw new Error("TARGET_PROFILE_REVIEW_LOSSLESS_PRIMARY_BOUNDARY_MISSING"); if (packet.index_role !== "MANDATORY_NAVIGATION_MAP_INTO_PRIMARY_EVIDENCE") throw new Error("TARGET_PROFILE_REVIEW_INDEX_NAVIGATION_BOUNDARY_MISSING"); if (packet.profile_forensics_inputs_allowed !== false) throw new Error("TARGET_PROFILE_REVIEW_FORENSICS_INPUT_BOUNDARY_MISSING"); }
function resolveTargetProfileReviewLockStatus(targetProfile = {}) { const explicit = targetProfile.lock_status || targetProfile.validation_status || targetProfile.status; if (LOCKED_STATUSES.has(explicit)) return explicit; if (hasControlledLimitationSignal(targetProfile)) return "LOCKED_WITH_LIMITATIONS"; return "LOCKED"; }
function hasControlledLimitationSignal(value) { if (!value) return false; if (typeof value === "string") return CONTROLLED_VALUES.has(value) || value.includes("FIELD_") || value.toUpperCase().includes("LIMITATION"); if (Array.isArray(value)) return value.length > 0 && value.some((item) => hasControlledLimitationSignal(item)); if (typeof value !== "object") return false; if (Array.isArray(value.target_profile_limitations) && value.target_profile_limitations.length) return true; return Object.values(value).some((item) => hasControlledLimitationSignal(item)); }
function assertSameArray(actual, expected, label) { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${label}_MISMATCH:${JSON.stringify({ actual, expected })}`); }
function assertCallback(fn, label) { if (typeof fn !== "function") throw new Error(`TARGET_PROFILE_REVIEW_RUNNER_MISSING_CALLBACK:${label}`); }
