import { asList, card, escapeHtml, metricCard, safeArray, section, table, text } from "./htmlReportPrimitives.js";

export function renderLegalStack(report) {
  const legal = report.legal_stack_control_review || {};
  return section("legal-stack", "04", "Legal Stack & Control Review", `
    ${card("Legal Stack & Control Review", `<h4>Legal Stack Synthesis</h4><p>${escapeHtml(text(legal.legal_stack_synthesis?.summary))}</p><h4>Document Inventory</h4>${table([{ label: "Document / Control Area", key: "document_type" }, { label: "Evidenced", render: (row) => escapeHtml(row.exists || row.evidenced ? "Yes" : "No") }, { label: "Status", key: "evidence_status" }, { label: "URL", render: (row) => row.document_url ? `<a href="${escapeHtml(row.document_url)}">Open document</a>` : "—" }, { label: "Controls Found", render: (row) => escapeHtml(text(row.controls_found)) }, { label: "Gaps Noted", render: (row) => escapeHtml(text(row.gaps_noted)) }], legal.document_inventory)}<h4>Document Coverage Matrix</h4>${table([{ label: "Document", key: "document_type" }, { label: "Evidenced", render: (row) => escapeHtml(row.evidenced ? "Yes" : "No") }, { label: "Coverage Purpose", key: "coverage_purpose" }, { label: "Linked Findings", render: (row) => escapeHtml(text(safeArray(row.linked_consolidated_findings).map((item) => `${item.consolidated_finding_id} ${item.exposure_title}`))) }], legal.document_coverage_matrix)}`)}
    ${card("Control-Evidenced Items", table([{ label: "Registry Reference", key: "registry_reference" }, { label: "Exposure Title", key: "exposure_title" }, { label: "Control Position", key: "control_position" }, { label: "Residual Watchpoint", key: "residual_watchpoint" }], legal.control_evidenced_items))}
    ${card("Control Gaps", table([{ label: "Document / Control", key: "document_type" }, { label: "Gap", key: "gap" }, { label: "Linked Findings", render: (row) => escapeHtml(text(safeArray(row.linked_consolidated_findings).map((item) => `${item.consolidated_finding_id} ${item.exposure_title}`))) }], legal.control_gaps))}
    ${card("Counsel Review Points", table([{ label: "Finding", key: "consolidated_finding_id" }, { label: "Exposure", key: "exposure_title" }, { label: "Affected Documents", render: (row) => escapeHtml(text(row.affected_documents)) }, { label: "Counsel Review Point", key: "counsel_review_point" }], legal.counsel_review_points))}
  `);
}

function findingCards(items) {
  return safeArray(items).map((finding, index) => `<details class="finding" ${index < 2 ? "open" : ""}><summary><b>${escapeHtml(text(finding.consolidated_finding_id))}</b> ${escapeHtml(text(finding.exposure_title))} <span>${escapeHtml(text(finding.highest_severity?.label || finding.severity?.label))}</span></summary><div class="grid"><div><h4>Finding Statement</h4><p>${escapeHtml(text(finding.finding_statement))}</p></div><div><h4>Evidence Basis</h4><p>${escapeHtml(text(finding.evidence_basis?.supporting_registry_references))}</p></div><div><h4>Legal Significance</h4><p>${escapeHtml(text(finding.legal_significance))}</p></div><div><h4>Control Position</h4><p>${escapeHtml(text(finding.control_position))}</p></div><div><h4>Affected Documents / Controls</h4><p>${escapeHtml(text(finding.affected_documents_controls?.affected_documents))}</p><p class="muted">${escapeHtml(text(finding.affected_documents_controls?.affected_controls))}</p></div><div><h4>Commercial / Deal Impact</h4><p>${escapeHtml(text(finding.commercial_deal_impact))}</p></div><div><h4>Recommended Remediation</h4><p>${escapeHtml(text(finding.recommended_remediation?.action))}</p></div><div><h4>Supporting Registry Items</h4><p>${escapeHtml(text(finding.supporting_registry_references))}</p></div></div>${table([{ label: "Registry Reference", key: "registry_reference" }, { label: "Exposure Item", key: "exposure_title" }, { label: "Severity", key: "severity" }, { label: "Timing", key: "timing_urgency" }, { label: "Control Position", key: "control_position" }], finding.supporting_registry_rows)}</details>`).join("") || `<p class="muted">No identified exposure findings were recorded.</p>`;
}

export function renderFindings(report) {
  const findings = report.exposure_findings || {};
  const gaps = report.evidence_gaps_clarification_points || {};
  const consolidated = safeArray(findings.consolidated_findings);
  const rows = safeArray(findings.supporting_registry_rows || findings.supporting_registry_items);
  return section("findings", "05", "Findings", `
    ${card("Exposure Findings", `<p class="muted">Consolidated exposure findings are the client-facing issue units. Registry rows are supporting proof, not the main report unit.</p>${table([{ label: "Finding", key: "consolidated_finding_id" }, { label: "Exposure Finding", key: "exposure_title" }, { label: "Supporting Items", key: "supporting_registry_item_count" }, { label: "Highest Severity", render: (row) => escapeHtml(text(row.highest_severity?.label || row.severity?.label)) }, { label: "Priority", render: (row) => escapeHtml(text(row.recommended_remediation?.priority)) }, { label: "Affected Documents", render: (row) => escapeHtml(text(row.affected_documents_controls?.affected_documents)) }], consolidated)}${findingCards(consolidated)}<details><summary>Open supporting registry exposure items (${rows.length})</summary>${table([{ label: "Registry Item", key: "registry_reference" }, { label: "Exposure Item", key: "exposure_title" }, { label: "Assessment", key: "assessment_outcome" }, { label: "Severity", key: "severity" }, { label: "Timing", key: "timing_urgency" }, { label: "Control Position", key: "control_position" }], rows)}</details>`)}
    ${card("Evidence Gaps & Clarification Points", `<h4>Open Information Request List</h4>${table([{ label: "Request", key: "request_id" }, { label: "Question", key: "question" }, { label: "Why It Matters", key: "why_it_matters" }, { label: "Evidence Requested", key: "evidence_requested" }, { label: "Priority", key: "priority" }, { label: "Consequence If Unresolved", key: "consequence_if_unresolved" }], gaps.open_information_request_list)}<h4>Missing Documents</h4>${table([{ label: "Document", key: "document_type" }, { label: "Requested Evidence", key: "requested_evidence" }], gaps.missing_documents)}<h4>Missing Factual Confirmations</h4>${table([{ label: "Registry Reference", key: "registry_reference" }, { label: "Exposure", key: "exposure_title" }, { label: "Clarification Points", render: (row) => escapeHtml(text(row.clarification_points)) }], gaps.missing_factual_confirmations)}`)}
  `);
}

export function renderRemediation(report) {
  const implications = report.implications_remediation_path || {};
  return section("remediation", "06", "Remediation Path", `${card("Implications & Remediation Path", `<p class="lead small">${escapeHtml(text(implications.matter_sensitivity, "Matter sensitivity not classified."))}</p><h4>Remediation Roadmap</h4>${table([{ label: "Finding", key: "consolidated_finding_id" }, { label: "Exposure", key: "exposure_title" }, { label: "Priority", key: "priority" }, { label: "Specific Action", key: "specific_action" }, { label: "Owner", key: "owner" }, { label: "Timing", key: "timing" }, { label: "Output", key: "output_document" }], implications.remediation_roadmap)}<h4>Document Route</h4>${asList(implications.document_route)}<h4>Control Route</h4>${asList(implications.control_route)}<h4>Review Priority</h4>${table([{ label: "Finding", key: "consolidated_finding_id" }, { label: "Exposure", key: "exposure_title" }, { label: "Priority", key: "priority" }, { label: "Counsel Review Point", key: "counsel_review_point" }], implications.review_priority)}<h4>Review-Ready Handoff Bridge</h4>${table([{ label: "Finding", key: "consolidated_finding_id" }, { label: "Output Document", key: "output_document" }, { label: "Document Route", render: (row) => escapeHtml(text(row.document_route)) }, { label: "Control Route", render: (row) => escapeHtml(text(row.control_route)) }, { label: "Open Question", key: "open_question" }], implications.review_ready_handoff_bridge)}`)}`);
}

export function renderAppendix(report) {
  const methodology = report.methodology_limitations_review_notes || {};
  const appendix = report.forensic_ledger_appendix || {};
  const ledger = safeArray(appendix.forensic_ledger);
  return section("appendix", "07", "Appendix", `${card("Methodology, Limitations & Review Notes", `<div class="light"><h4>Methodology</h4>${asList(methodology.methodology)}<h4>Stage Roles</h4>${asList(methodology.stage_roles)}<h4>Status Definitions</h4>${table([{ label: "Status", key: "status" }, { label: "Meaning", key: "meaning" }], methodology.status_definitions)}<h4>Legal Limitations</h4>${asList(methodology.legal_limitations)}<h4>Evidence Limitations</h4>${asList(methodology.evidence_limitations)}<div class="notice dark">${escapeHtml(text(methodology.counsel_review_note))}</div></div>`)}${card("Forensic Ledger Appendix", `<div class="metrics">${metricCard("Registry Count", appendix.registry_count || 0)}${metricCard("Ledger Count", appendix.ledger_count || 0)}${Object.entries(appendix.status_counts || {}).map(([key, value]) => metricCard(key, value)).join("")}</div><details open><summary>Open full forensic ledger (${ledger.length} rows)</summary>${table([{ label: "Registry Reference", key: "registry_reference" }, { label: "Exposure Title", key: "exposure_title" }, { label: "Assessment Outcome", key: "assessment_outcome" }, { label: "Severity", render: (row) => escapeHtml(text(row.severity?.label || row.severity)) }, { label: "Timing", render: (row) => escapeHtml(text(row.timing_urgency?.label || row.timing_urgency)) }, { label: "Functional Profile", render: (row) => escapeHtml(text(row.functional_profile?.label || row.functional_profile)) }, { label: "Evidence Reference", render: (row) => escapeHtml(text(row.evidence_references?.evidence_reference)) }, { label: "Finding Threshold", key: "finding_threshold_outcome" }, { label: "Control Test", key: "control_test_outcome" }, { label: "Status Explanation", key: "status_explanation" }], ledger)}</details>`)}`);
}
