import assemblyOutputSchema from "../../../../data/schemas/assemblyOutput.schema.json";
import compilerOutputSchema from "../../../../data/schemas/compilerOutput.schema.json";
import { createHandoffEnvelope, validateHandoffEnvelope } from "../../contracts/handoffEnvelope.js";
import { formatSchemaErrors, validateJsonSchema } from "../validation/jsonSchemaValidator.js";
import { FORBIDDEN_NODE5B_INPUT_FIELDS, getVaultGroup, isAllowedVaultPath, normalizeVaultFieldPath } from "./vaultAllowlist.js";

const ARCHETYPE_PREFILL_MAP = Object.freeze({ UNI: ["archetypes.is_generalist"], DOE: ["archetypes.is_doer"], ORC: ["archetypes.is_orchestrator"], CRT: ["archetypes.is_creator"], RDR: ["archetypes.is_reader"], CMP: ["archetypes.conversational_ui"], TRN: ["archetypes.sens_bio"], JDG: ["archetypes.is_judge", "archetypes.is_judge_hr", "archetypes.is_judge_legal"], OPT: ["archetypes.is_optimizer", "archetypes.sens_fin"], SHD: ["archetypes.is_shield"], MOV: ["archetypes.is_mover"] });
const SURFACE_PREFILL_MAP = Object.freeze({ PII: [["compliance.processes_pii", "yes"]], Financial: [["compliance.sens_fin", true]], Employment: [["compliance.sens_employment", true]], Minors: [["compliance.minors", true]] });
function nowIso() { return new Date().toISOString(); }
function hasOwn(object, key) { return Object.prototype.hasOwnProperty.call(object || {}, key); }
function warning(code, message) { return `W001 | ${code} | ${message}`; }
function createEmptyVaultPrefill() { return { baseline: {}, architecture: {}, archetypes: {}, compliance: {} }; }
function createSuggestion(value, basis, confidence = "high", sourceFindingIds = []) { return { value, basis, confidence, source_finding_ids: Array.isArray(sourceFindingIds) ? sourceFindingIds.map(String) : [] }; }
function asObject(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function asArray(value) { return Array.isArray(value) ? value : []; }
function asString(value, fallback = "") { if (value === undefined || value === null) return fallback; const s = String(value).trim(); return s || fallback; }
function setPrefill(prefill, fieldPath, suggestion, warnings) { const normalizedPath = normalizeVaultFieldPath(fieldPath); const group = getVaultGroup(normalizedPath); if (!group || !isAllowedVaultPath(normalizedPath)) { warnings.push(warning("INVALID_VAULT_PATH", `Skipped invalid Vault field path: ${fieldPath}`)); return false; } const localPath = normalizedPath.split(".").slice(1).join("."); prefill[group][localPath] = suggestion; return true; }
function targetProfile(compilerOutput) { return asObject(compilerOutput.target_profile_v2); }
function featureProfile(compilerOutput) { return asObject(compilerOutput.feature_profile_v2); }
function featureInventory(compilerOutput) { return asArray(featureProfile(compilerOutput).feature_inventory); }
function candidateValue(candidate) { const c = asObject(candidate); return c.status === "PREFILL_READY" && c.value !== undefined && c.value !== null && String(c.value).trim() !== "" ? c : null; }
function applyCandidate(prefill, path, candidate, warnings) { const c = candidateValue(candidate); if (!c) return; setPrefill(prefill, path, createSuggestion(c.value, c.basis || `Derived from canonical ${path} candidate.`, c.confidence || "high", c.evidence_refs || []), warnings); }
function collectArchetypeCodes(compilerOutput) { const codes = []; featureInventory(compilerOutput).forEach((f) => asArray(f.archetype_codes).forEach((c) => codes.push(String(c || "").toUpperCase()))); asArray(compilerOutput.findings).forEach((f) => codes.push(String(f.archetype || f.archetype_code || "").toUpperCase())); return [...new Set(codes.filter(Boolean))]; }
function getFindingIdsForArchetype(compilerOutput, code) { return asArray(compilerOutput.findings).filter((f) => String(f.archetype || "").toUpperCase().includes(code)).map((f) => f.finding_id || f.threat_id).filter(Boolean); }
function deriveArchetypePrefill(compilerOutput, prefill, warnings) { collectArchetypeCodes(compilerOutput).forEach((code) => { const paths = ARCHETYPE_PREFILL_MAP[code]; if (!paths) return; paths.forEach((path) => setPrefill(prefill, path, createSuggestion(true, `Derived from canonical feature/finding archetype ${code}.`, "high", getFindingIdsForArchetype(compilerOutput, code)), warnings)); }); }
function collectSurfaceTokens(compilerOutput) { const tokens = []; featureInventory(compilerOutput).forEach((f) => asArray(f.surface_tokens).forEach((s) => tokens.push(String(s || "")))); asArray(featureProfile(compilerOutput).regulated_surface_map).forEach((s) => tokens.push(String(s.surface_token || ""))); return [...new Set(tokens.filter(Boolean))]; }
function deriveSurfacePrefill(compilerOutput, prefill, warnings) { collectSurfaceTokens(compilerOutput).forEach((token) => { (SURFACE_PREFILL_MAP[token] || []).forEach(([path, value]) => setPrefill(prefill, path, createSuggestion(value, `Derived from canonical Stage 5 surface token ${token}.`, "high", []), warnings)); }); }
function deriveBaselinePrefill(compilerOutput, prefill, warnings) { const profile = targetProfile(compilerOutput); const id = asObject(profile.identity); const baseline = asObject(asObject(profile.vault_baseline_candidates).baseline); applyCandidate(prefill, "baseline.company", baseline.company, warnings); applyCandidate(prefill, "baseline.entity_type", baseline.entity_type, warnings); applyCandidate(prefill, "baseline.address", baseline.address, warnings); applyCandidate(prefill, "baseline.legal_email", baseline.legal_email, warnings); applyCandidate(prefill, "baseline.privacy_email", baseline.privacy_email, warnings); applyCandidate(prefill, "baseline.products", baseline.products, warnings); applyCandidate(prefill, "baseline.jurisdiction.country", asObject(baseline.jurisdiction).country, warnings); applyCandidate(prefill, "baseline.jurisdiction.state", asObject(baseline.jurisdiction).state, warnings); applyCandidate(prefill, "baseline.market", baseline.market, warnings); applyCandidate(prefill, "baseline.delivery.app", asObject(baseline.delivery).app, warnings); applyCandidate(prefill, "baseline.delivery.api", asObject(baseline.delivery).api, warnings); applyCandidate(prefill, "baseline.revenue_model", baseline.revenue_model, warnings); applyCandidate(prefill, "baseline.has_beta", baseline.has_beta, warnings); const integrations = asObject(baseline.integrations); ["slack", "crm", "stripe", "github", "webhooks", "none"].forEach((key) => applyCandidate(prefill, `baseline.integrations.${key}`, integrations[key], warnings)); if (!prefill.baseline.company) { const name = id.legal_name || id.brand_name; if (name) setPrefill(prefill, "baseline.company", createSuggestion(name, "Derived from canonical target_profile_v2.identity with legal_name priority.", "high", ["target_profile_v2.identity"]), warnings); } if (!prefill.baseline.products) { const products = [...new Set(featureInventory(compilerOutput).map((f) => f.business_label_or_product_area || f.feature_name).filter(Boolean))]; if (products.length) setPrefill(prefill, "baseline.products", createSuggestion(products, "Derived from canonical feature_inventory business labels.", "medium", ["feature_profile_v2.feature_inventory"]), warnings); } }
function deriveArchitecturePrefill(compilerOutput, prefill, warnings) { asArray(featureProfile(compilerOutput).architecture_hints).filter((h) => h.disposition === "prefill_candidate").forEach((hint) => { const type = hint.hint_type; const value = hint.hint_value; const basis = `Derived from explicit Stage 5 architecture_hints entry ${hint.hint_id || ""}.`; if (!value) return; if (type === "memory") setPrefill(prefill, "architecture.memory", createSuggestion(value, basis, hint.confidence || "medium", [hint.feature_id].filter(Boolean)), warnings); if (type === "cloud_host") setPrefill(prefill, "architecture.cloud_host", createSuggestion(value, basis, hint.confidence || "medium", [hint.feature_id].filter(Boolean)), warnings); if (type === "vector_db") setPrefill(prefill, "architecture.vector_db", createSuggestion(value, basis, hint.confidence || "medium", [hint.feature_id].filter(Boolean)), warnings); if (type === "model_provider" || type === "subprocessor") setPrefill(prefill, "architecture.sub_processors.other", createSuggestion(value, basis, hint.confidence || "medium", [hint.feature_id].filter(Boolean)), warnings); }); }
function transformConfirmationQuestions(compilerOutput, warnings) { return asArray(compilerOutput.vault_confirmation_questions).flatMap((question) => { const originalPath = question.field_path; const normalizedPath = normalizeVaultFieldPath(originalPath); if (originalPath !== normalizedPath) warnings.push(warning("SCHEMA_BRIDGE_TRANSFORM", `Mapped ${originalPath} to ${normalizedPath}.`)); if (!isAllowedVaultPath(normalizedPath)) { warnings.push(warning("INVALID_VAULT_PATH", `Excluded confirmation question for invalid Vault path: ${originalPath}`)); return []; } return [{ field_path: normalizedPath, question: question.question || `Please confirm ${normalizedPath}.`, why_it_matters: question.why_it_matters || "Required for Assembly document routing.", source_context: Array.isArray(question.source_finding_ids) && question.source_finding_ids.length ? `source_finding_ids=${question.source_finding_ids.join(",")}` : "source_finding_ids=none", required_for: compilerOutput.assembly_route?.recommended_package || "Assembly routing and local counsel review" }]; }); }
function deriveThreatFindings(compilerOutput) { if (Array.isArray(compilerOutput.threat_findings) && compilerOutput.threat_findings.length) return compilerOutput.threat_findings; return asArray(compilerOutput.findings).map((finding) => ({ finding_id: finding.finding_id, threat_id: finding.threat_id, threat_name: finding.threat_name, linked_feature_ids: finding.linked_feature_ids || [], document_routes: finding.document_routes || finding.redline_route || [], vault_dependencies: finding.vault_dependencies || [], severity: finding.pain_tier || finding.pain_depth || "UNSPECIFIED", status: "TRIGGERED" })); }
function validateCompilerInput(compilerOutput) { const errors = []; const schemaValidation = validateJsonSchema(compilerOutputSchema, compilerOutput); if (!schemaValidation.ok) errors.push(`COMPILER_SCHEMA_INVALID: ${formatSchemaErrors(schemaValidation.errors)}`); FORBIDDEN_NODE5B_INPUT_FIELDS.forEach((field) => { if (hasOwn(compilerOutput, field)) errors.push(`FORBIDDEN_BACKEND_FIELD: compiler output contains ${field}`); }); return errors; }
function createSummary(compilerOutput) { const id = asObject(targetProfile(compilerOutput).identity); const company = id.legal_name || id.brand_name || "target"; const feature = featureInventory(compilerOutput)[0]?.feature_name || "feature inventory"; return `Assembly handoff for ${company} / ${feature}`; }
export function assembleNode5B(compilerOutput, options = {}) { const compilerErrors = validateCompilerInput(compilerOutput); if (compilerErrors.length) return { ok: false, error_type: "COMPILER_OUTPUT_INVALID", errors: compilerErrors }; const warnings = []; const runId = compilerOutput?.diligence_run?.run_id || compilerOutput?.run_id || `run-${Date.now()}`; const createdAt = options.createdAt || nowIso(); const vault_prefill_suggestions = createEmptyVaultPrefill(); deriveArchetypePrefill(compilerOutput, vault_prefill_suggestions, warnings); deriveSurfacePrefill(compilerOutput, vault_prefill_suggestions, warnings); deriveBaselinePrefill(compilerOutput, vault_prefill_suggestions, warnings); deriveArchitecturePrefill(compilerOutput, vault_prefill_suggestions, warnings); const vault_confirmation_questions = transformConfirmationQuestions(compilerOutput, warnings); const assembly_handoff = { handoff_meta: { run_id: runId, created_at: createdAt, source_engine: "diligence", target_engine: "assembly", compiler_schema: "compilerOutput.schema.json", assembler_contract: "NODE_5B_DETERMINISTIC_ASSEMBLER_CONTRACT_v1" }, target_profile: targetProfile(compilerOutput), feature_map: featureInventory(compilerOutput), threat_findings: deriveThreatFindings(compilerOutput), document_stack_status: compilerOutput.legal_stack || [], vault_prefill_suggestions, vault_confirmation_questions, assembly_route_recommendation: compilerOutput.assembly_route || {}, warnings };
  const assemblyValidation = validateJsonSchema(assemblyOutputSchema, assembly_handoff); if (!assemblyValidation.ok) return { ok: false, error_type: "ASSEMBLY_OUTPUT_INVALID", errors: assemblyValidation.errors, error_summary: formatSchemaErrors(assemblyValidation.errors), assembly_handoff }; const handoff_id = options.handoffId || undefined; const payloadRef = options.payloadRef || `interface_handoff_payloads/${handoff_id || "pending"}`; const handoff_envelope = createHandoffEnvelope({ runId, sourceEngine: "diligence", targetEngine: "assembly", payloadType: "assembly_handoff_payload", payloadRef, summary: createSummary(compilerOutput), warnings }); const envelopeValidation = validateHandoffEnvelope(handoff_envelope); if (!envelopeValidation.valid) return { ok: false, error_type: "HANDOFF_ENVELOPE_INVALID", errors: envelopeValidation.errors, assembly_handoff, handoff_envelope }; const payload_ref = payloadRef === "interface_handoff_payloads/pending" ? `interface_handoff_payloads/${handoff_envelope.handoff_id}` : payloadRef; return { ok: true, node: "5B", run_id: runId, vault_prefill_suggestions, assembly_handoff, handoff_envelope: { ...handoff_envelope, payload_ref }, persistence_plan: { payload_collection: "interface_handoff_payloads", envelope_collection: "interface_handoffs", stage_output_path: `interface_runs/${runId}/stage_outputs/node_5b_backend_assembler`, payload_ref }, warnings }; }
export function assertNode5BAssembled(result) { if (!result?.ok) throw new Error(`Node 5B assembly failed: ${(result?.errors || [result?.error_type || "unknown error"]).join(" | ")}`); return result; }
