export * from "./runtime/contracts/artifact-permissions.contract.js";
export { INTERNAL_JOB_WRITE_PERMISSIONS as PHASE_WRITE_PERMISSIONS } from "./runtime/contracts/artifact-permissions.contract.js";

export const SERVICE_NAME = "interface-diligence-artifacts";
export const QUALIFIED_REVIEW_SYSTEM_AGENT = "qualified_review_system";
export const NORMALIZED_COMPILER_PHASE = "NORMALIZED_COMPILER";
export const PHASES = Object.freeze([
  "AGENT_1A_URL_MANIFEST",
  "AGENT_1B_EXTRACT",
  "M6_BUCKET_INDEX",
  "M9",
  "M7_TARGET_PROFILE",
  "M7_TARGET_PROFILE_FORENSICS",
  "M8_FEATURE_CANDIDATE_INVENTORY",
  "M8_TARGET_FEATURE_PROFILE",
  "M8_TARGET_FEATURE_PROFILE_FORENSICS",
  "DATA_PROVENANCE_PROFILE_LAYER4",
  "DATA_PROVENANCE_PROFILE_LAYER5",
  "M11",
  "M12",
  "NORMALIZED_COMPILER",
  "QUALIFIED_REVIEW_HANDOFF",
  "QUALIFIED_REVIEW_RENDERER",
  "QUALIFIED_REVIEW_SUBMISSION",
  "RENDERER",
  "COMPLETE"
]);
export const LOCK_STATUSES = Object.freeze(["CREATED", "RUNNING", "LOCKED", "LOCKED_WITH_LIMITATIONS", "REPAIR_REQUIRED", "CONTROLLED_FAILURE", "COMPLETE"]);
