import { TARGET_PROFILE_FORENSICS_CONTRACT } from "./target-profile-forensics.contract.js";
import { buildM7DeterministicTargetForensics } from "../_shared/forensics/profile-forensics.shared.js";
import { readPhaseRouteRuntimePacket } from "../02-cartography-index/services/phase-route-runtime.reader.js";

export const TARGET_PROFILE_FORENSICS_RUNNER_STATUS = Object.freeze({ phase_runner: "target-profile-forensics.runner", central_phase_id: TARGET_PROFILE_FORENSICS_CONTRACT.central_phase_id, public_label: TARGET_PROFILE_FORENSICS_CONTRACT.public_label, phase_owned_runner: true, production_entrypoint_switched: true, global_production_deployment_switched: false, model_usage: "NONE_DETERMINISTIC", source_helper: TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.source_helper, phase2g_route_scoped_runtime_reader_active: true, delivery_mode: "DERIVED_ONLY", source_bucket_delivered: false, profile_forensics_inputs_forbidden: true, writes: [...TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.writes], routing_manifest_read: "phase_routing_manifest" });

export async function runTargetProfileForensicsPhase({ run, internalJobId = "M7_TARGET_PROFILE_FORENSICS", contract, readArtifacts, saveArtifact } = {}) {
  assertRuntimeContract(contract); assertCallback(readArtifacts, "readArtifacts"); assertCallback(saveArtifact, "saveArtifact");
  const routed = await readPhaseRouteRuntimePacket({ internalJobId, readArtifacts, consumerAgentId: contract.agent_id || contract.actor_id });
  const artifacts = routed.artifacts;
  assertRoutePacket(artifacts.phase_route_runtime_packet, internalJobId);
  assertAllowedRuntimeArtifacts(artifacts);
  const output = buildM7DeterministicTargetForensics({ artifacts });
  const artifactName = contract.writes[0];
  const artifact = output?.[artifactName];
  if (!artifact || typeof artifact !== "object" || Array.isArray(artifact)) throw new Error(`TARGET_PROFILE_FORENSICS_OUTPUT_MISSING_ARTIFACT:${artifactName}`);
  assertForensicOutputContract(artifact); assertForensicBoundary(artifact);
  const phaseLockStatus = resolveForensicLockStatus(artifact);
  await saveArtifact({ artifact_name: artifactName, artifact, lock_status: phaseLockStatus });
  return { ok: true, output, saved_artifacts: [artifactName], phase_lock_status: phaseLockStatus, artifacts_read: Object.keys(artifacts).sort(), model_usage: "NONE_DETERMINISTIC", phase2g_route_id: routed.route.route_id, phase2g_bucket_id: routed.route.bucket_id, phase2g_delivery_mode: routed.route.delivery_mode, target_profile_forensics_phase_runner_used: true, source_helper: TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.source_helper, validator: TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.validator };
}
function assertRuntimeContract(contract = {}) { if (contract.central_phase_id !== TARGET_PROFILE_FORENSICS_CONTRACT.central_phase_id) throw new Error(`TARGET_PROFILE_FORENSICS_CONTRACT_MISMATCH:${contract.central_phase_id || "missing"}`); if (contract.public_label !== TARGET_PROFILE_FORENSICS_CONTRACT.public_label) throw new Error(`TARGET_PROFILE_FORENSICS_LABEL_MISMATCH:${contract.public_label || "missing"}`); if (!(contract.reads || []).includes("phase_routing_manifest")) throw new Error("TARGET_PROFILE_FORENSICS_PHASE2G_MANIFEST_READ_MISSING"); assertSameArray(contract.writes || [], TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.writes, "TARGET_PROFILE_FORENSICS_WRITES"); }
function assertRoutePacket(packet = {}, internalJobId) { if (packet.routing_authority !== "P2G_CENTRALIZED_PHASE_ROUTING_AUTHORITY") throw new Error("TARGET_PROFILE_FORENSICS_PHASE2G_AUTHORITY_MISSING"); if (packet.internal_job_id !== internalJobId) throw new Error(`TARGET_PROFILE_FORENSICS_PHASE2G_JOB_MISMATCH:${packet.internal_job_id || "missing"}`); if (packet.route_id !== "ROUTE.PHASE3A.TARGET_PROFILE") throw new Error(`TARGET_PROFILE_FORENSICS_PHASE2G_ROUTE_MISMATCH:${packet.route_id || "missing"}`); if (packet.delivery_mode !== "DERIVED_ONLY") throw new Error(`TARGET_PROFILE_FORENSICS_PHASE2G_DELIVERY_MODE_MISMATCH:${packet.delivery_mode || "missing"}`); if (packet.source_bucket_delivered !== false) throw new Error("TARGET_PROFILE_FORENSICS_SOURCE_BUCKET_DELIVERED"); if (packet.profile_forensics_inputs_allowed !== false) throw new Error("TARGET_PROFILE_FORENSICS_FORENSICS_INPUT_BOUNDARY_MISSING"); }
function assertAllowedRuntimeArtifacts(artifacts = {}) { const allowed = new Set(TARGET_PROFILE_FORENSICS_CONTRACT.deterministic_job.reads); for (const key of Object.keys(artifacts)) if (!allowed.has(key)) throw new Error(`TARGET_PROFILE_FORENSICS_FORBIDDEN_RUNTIME_ARTIFACT:${key}`); }
function assertForensicOutputContract(artifact = {}) { for (const branch of TARGET_PROFILE_FORENSICS_CONTRACT.output_contract.required_branches) if (!(branch in artifact)) throw new Error(`TARGET_PROFILE_FORENSICS_MISSING_BRANCH:${branch}`); for (const branch of TARGET_PROFILE_FORENSICS_CONTRACT.output_contract.array_branches) if (!Array.isArray(artifact[branch])) throw new Error(`TARGET_PROFILE_FORENSICS_BRANCH_NOT_ARRAY:${branch}`); }
function assertForensicBoundary(artifact = {}) { if (artifact?.forensic_contract?.model_generated_forensics_allowed !== false) throw new Error("TARGET_PROFILE_FORENSICS_MODEL_GENERATED_TRACE_NOT_FORBIDDEN"); if (artifact?.forensic_boundary?.material_profile_re_emitted !== false) throw new Error("TARGET_PROFILE_FORENSICS_MATERIAL_PROFILE_REEMISSION_NOT_FORBIDDEN"); if (artifact?.forensic_boundary?.semantic_forensic_profile_retired !== true) throw new Error("TARGET_PROFILE_FORENSICS_SEMANTIC_FORENSICS_NOT_RETIRED"); if (!artifact.forensic_lock_gate_result || typeof artifact.forensic_lock_gate_result !== "object") throw new Error("TARGET_PROFILE_FORENSICS_MISSING_LOCK_GATE"); }
function resolveForensicLockStatus(artifact = {}) { const status = artifact.forensic_lock_gate_result?.status || artifact.validation_quality_control_result?.status; if (status === "PASS") return "LOCKED"; if (status === "PASS_WITH_LIMITATION") return "LOCKED_WITH_LIMITATIONS"; return "REPAIR_REQUIRED"; }
function assertSameArray(actual, expected, label) { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`${label}_MISMATCH:${JSON.stringify({ actual, expected })}`); }
function assertCallback(fn, label) { if (typeof fn !== "function") throw new Error(`TARGET_PROFILE_FORENSICS_RUNNER_MISSING_CALLBACK:${label}`); }
