name = "interface-diligence-system-proxy"
main = "src/index.js"
compatibility_date = "2026-06-29"
workers_dev = false

routes = [
  { pattern = "sandbox.lexnovahq.com", zone_name = "lexnovahq.com" },
  { pattern = "sandbox.lexnovahq.com/interface-diligence/diligence-system*", zone_name = "lexnovahq.com" },
  { pattern = "sandbox.lexnovahq.com/public*", zone_name = "lexnovahq.com" },
  { pattern = "sandbox.lexnovahq.com/vault*", zone_name = "lexnovahq.com" },
  { pattern = "sandbox.lexnovahq.com/health", zone_name = "lexnovahq.com" }
]
