import { deriveVaultPrefillFromStage9 } from "./vaultPrefillFromStage9.js";
import { deriveVaultQuestionsFromStage9 } from "./vaultQuestionsFromStage9.js";

const asArray = (value) => Array.isArray(value) ? value : [];
const asObject = (value) => value && typeof value === "object" && !Array.isArray(value) ? value : {};
function nowIso() { return new Date().toISOString(); }
function createId(prefix) { const randomPart = globalThis.crypto && typeof globalThis.crypto.randomUUID === "function" ? globalThis.crypto.randomUUID() : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`; return `${prefix}_${randomPart}`; }
function report(stage9) { return stage9?.report?.report_data || stage9?.report_data || stage9; }
function getRunId(stage9) { const data = report(stage9); return stage9?.run_id || stage9?.report?.run_id || data?.diligence_run?.run_id || data?.matter_overview?.run_id || stage9?.report_meta?.run_id || `run-${Date.now()}`; }
function targetProfile(stage9) { const data = report(stage9); return asObject(data.target_profile_v2 || stage9?.target_profile_v2 || stage9?.compiler_output?.target_profile_v2); }
function featureProfile(stage9) { const data = report(stage9); return asObject(data.feature_profile_v2 || stage9?.feature_profile_v2 || stage9?.compiler_output?.feature_profile_v2); }
function featureInventory(stage9) { return asArray(featureProfile(stage9).feature_inventory).map((feature, index) => ({ ...asObject(feature), feature_id: feature?.feature_id || `stage9-feature-${index + 1}`, feature_name: feature?.feature_name || `Feature ${index + 1}` })); }
function deriveThreatFindings(stage9) { const data = report(stage9); if (Array.isArray(data.threat_findings) && data.threat_findings.length) return data.threat_findings; return asArray(data.findings).map((finding) => ({ finding_id: finding.finding_id, threat_id: finding.threat_id, threat_name: finding.threat_name, linked_feature_ids: finding.linked_feature_ids || [], document_routes: finding.document_routes || finding.redline_route || [], vault_dependencies: finding.vault_dependencies || [], severity: finding.pain_tier || finding.pain_depth || "UNSPECIFIED", status: "TRIGGERED" })); }
function deriveDocumentStackStatus(stage9) { const data = report(stage9); return asArray(data.legal_stack).length ? data.legal_stack : asArray(data.document_stack_redline); }
function deriveAssemblyRoute(stage9) { const data = report(stage9); return { ...asObject(data.assembly_route), local_counsel_review_required: data.assembly_route?.local_counsel_review_required === false ? false : true }; }
function createHandoffEnvelope({ runId, payloadRef, summary, warnings }) { const timestamp = nowIso(); return { handoff_id: createId("handoff"), run_id: runId, source_engine: "diligence", target_engine: "assembly", payload_type: "assembly_handoff_payload", status: "draft", created_at: timestamp, updated_at: timestamp, payload_ref: payloadRef, summary, warnings: Array.isArray(warnings) ? warnings : [String(warnings)] }; }
function createSummary(target, findings) { const id = asObject(target.identity); const name = id.legal_name || id.brand_name || target.company_name || "target"; return `Review-Ready remediation handoff for ${name} (${findings.length} finding route${findings.length === 1 ? "" : "s"}).`; }
export function assembleStage10VaultHandoff(stage9ReportData, options = {}) { const warnings = []; const runId = options.runId || getRunId(stage9ReportData); const createdAt = options.createdAt || nowIso(); const target = targetProfile(stage9ReportData); const features = featureInventory(stage9ReportData); const threatFindings = deriveThreatFindings(stage9ReportData); const documentStackStatus = deriveDocumentStackStatus(stage9ReportData); const vault_prefill_suggestions = deriveVaultPrefillFromStage9(stage9ReportData, warnings); const vault_confirmation_questions = deriveVaultQuestionsFromStage9(stage9ReportData); const assembly_route_recommendation = deriveAssemblyRoute(stage9ReportData); const assembly_handoff = { handoff_meta: { run_id: runId, created_at: createdAt, source_engine: "diligence", target_engine: "assembly", compiler_schema: "compilerOutput.schema.json", assembler_contract: "STAGE_10_STAGE9_TO_NODE_5B_COMPATIBLE_HANDOFF_v1", canonical_output_shape: "assembly_handoff_payload" }, target_profile: target, feature_map: features, threat_findings: threatFindings, document_stack_status: documentStackStatus, vault_prefill_suggestions, vault_confirmation_questions, assembly_route_recommendation, warnings };
  const pendingPayloadRef = options.payloadRef || "interface_handoff_payloads/pending"; const handoff_envelope = createHandoffEnvelope({ runId, payloadRef: pendingPayloadRef, summary: createSummary(target, threatFindings), warnings }); const payload_ref = pendingPayloadRef === "interface_handoff_payloads/pending" ? `interface_handoff_payloads/${handoff_envelope.handoff_id}` : pendingPayloadRef; return { ok: true, stage: "10", node: "5B_COMPAT_RUNTIME", run_id: runId, vault_prefill_suggestions, assembly_handoff, handoff_envelope: { ...handoff_envelope, payload_ref }, persistence_plan: { payload_collection: "interface_handoff_payloads", envelope_collection: "interface_handoffs", stage_output_path: `interface_runs/${runId}/stage_outputs/stage_10_review_ready_handoff`, payload_ref }, warnings }; }
