import { isAllowedVaultPath, normalizeVaultFieldPath } from "./vaultCanonicalMap.js";

export const FUNCTIONAL_SECTION_DEFS = Object.freeze({
  company_jurisdiction_contacts: { label: "Company, Jurisdiction & Contacts", role: "Confirm the legal target, notice details, jurisdiction, and regional posture." },
  product_delivery_commercial_model: { label: "Product, Delivery & Commercial Model", role: "Confirm product scope, delivery channels, integrations, customer model, and commercial posture." },
  ai_functionality_autonomy_user_reliance: { label: "AI Functionality, Autonomy & User Reliance", role: "Confirm the product's AI behavior, autonomy, human review, and reliance surfaces." },
  data_users_regulated_surfaces: { label: "Data, Users & Regulated Surfaces", role: "Confirm personal/sensitive data, users, regions, and regulated data surfaces." },
  technical_architecture_ai_supply_chain_integrations: { label: "Technical Architecture, AI Supply Chain & Integrations", role: "Confirm AI providers, upstream subprocessors, downstream integrations, hosting, logging, security, and API configuration." },
  contracting_output_customer_commitments: { label: "Contracting, Output Ownership & Customer Commitments", role: "Confirm commercial commitments, output ownership, SLA, reliance threshold, and customer-facing legal posture." },
  operational_controls_human_review_incident_handling: { label: "Operational Controls, Human Review & Incident Handling", role: "Confirm human approval gates, logging, escalation, incident response, and fallback/shutdown rules." },
  document_assembly_instructions: { label: "Document Assembly Instructions", role: "Confirm package, document routes, drafting mode, style, and output options for final assembly." },
  counsel_review_localisation: { label: "Counsel Review & Localisation", role: "Confirm jurisdictional treatment, local counsel review queue, source materials, and unresolved gap policy." }
});

const AI_PROVIDER_OPTIONS = Object.freeze(["openai", "anthropic", "google_gemini", "cohere", "mistral", "meta_llama", "deepseek", "xai", "azure_openai", "aws_bedrock", "self_hosted_oss", "other", "unknown"]);
const asArray = (value) => Array.isArray(value) ? value : [];
const asText = (value, fallback = "") => String(value ?? "").trim() || fallback;
const unique = (values = []) => [...new Set(asArray(values).map((value) => asText(value)).filter(Boolean))];
const validPaths = (paths = []) => unique(paths.map(normalizeVaultFieldPath)).filter(isAllowedVaultPath);

function dataFlows(packet = {}) {
  const data = packet.data_provenance_profile || packet.profile_handoffs?.data_provenance_profile || {};
  return asArray(data.integrated_feature_data_flow_profile || data.data_flow_profile || data.feature_data_flow_profile || data.data_flows);
}
function createQuestion({ sectionKey, questionKey, question, answerType = "text", options = [], vaultMatch = "none", vaultPaths = [], assemblyPaths = [], priority = "medium", requiredFor = [], prefillStatus = "needs_confirmation", matchNotes = "", whyItMatters = "", sourceContext = "", evidenceRefs = [], relatedFindingIds = [], relatedDocumentRoutes = [], relatedDataFlowIds = [], allowedValues = [] }) {
  return { section_key: sectionKey, section_label: FUNCTIONAL_SECTION_DEFS[sectionKey]?.label || sectionKey, question_key: questionKey, question, answer_type: answerType, options, vault_match: vaultMatch, vault_paths: validPaths(vaultPaths), assembly_paths: unique(assemblyPaths), priority, required_for: unique(requiredFor), prefill_status: prefillStatus, match_notes: matchNotes, why_it_matters: whyItMatters, source_context: sourceContext, evidence_refs: unique(evidenceRefs), related_finding_ids: unique(relatedFindingIds), related_document_routes: unique(relatedDocumentRoutes), related_data_flow_ids: unique(relatedDataFlowIds), allowed_values: allowedValues };
}
function addQuestion(questions, question) { const key = `${question.section_key}.${question.question_key}`; if (!questions.some((existing) => `${existing.section_key}.${existing.question_key}` === key)) questions.push(question); }
function sectionWarningsFor(sectionKey, questions = []) { const sectionQuestions = questions.filter((q) => q.section_key === sectionKey); const manualOnly = sectionQuestions.filter((q) => q.prefill_status === "manual_only").length; const partial = sectionQuestions.filter((q) => q.vault_match === "partial").length; return [manualOnly ? `${manualOnly} question(s) require manual input because they are not provable from diligence evidence.` : "", partial ? `${partial} question(s) map partially to Vault payload and also feed Assembly instructions.` : ""].filter(Boolean); }
export function buildFunctionalSections(questions = []) { return Object.fromEntries(Object.entries(FUNCTIONAL_SECTION_DEFS).map(([sectionKey, def]) => { const sectionQuestions = questions.filter((question) => question.section_key === sectionKey); const unanswered = sectionQuestions.filter((question) => ["needs_confirmation", "manual_only", "unknown"].includes(question.prefill_status)).length; return [sectionKey, { section_key: sectionKey, section_label: def.label, section_role: def.role, completion_status: unanswered ? "needs_confirmation" : "complete", prefill_summary: sectionQuestions.length ? `${sectionQuestions.length} intake question(s), ${unanswered} requiring confirmation/manual input.` : "No questions generated for this section.", questions: sectionQuestions, section_warnings: sectionWarningsFor(sectionKey, sectionQuestions) }]; })); }

export function deriveVaultQuestionsFromStage10SourcePacket(packet = {}) {
  const questions = [];
  addQuestion(questions, createQuestion({ sectionKey: "company_jurisdiction_contacts", questionKey: "confirm_company_name", question: "Please confirm the legal company name that should appear in the documents.", answerType: "text", vaultMatch: "perfect", vaultPaths: ["baseline.company"], priority: "critical", requiredFor: ["Matter profile", "Terms", "Privacy Policy", "DPA"], prefillStatus: packet.target_profile?.company_name && packet.target_profile.company_name !== "Unknown target" ? "prefilled" : "manual_only", sourceContext: "Mapped from target_profile.identity." }));
  addQuestion(questions, createQuestion({ sectionKey: "company_jurisdiction_contacts", questionKey: "confirm_jurisdiction", question: "Please confirm primary legal jurisdiction and state/province, if applicable.", answerType: "object", vaultMatch: "perfect", vaultPaths: ["baseline.jurisdiction.country", "baseline.jurisdiction.state"], assemblyPaths: ["assembly_handoff_intake.localisation.primary_jurisdiction"], priority: "critical", requiredFor: ["Local counsel review", "Governing law placeholders"], prefillStatus: packet.target_profile?.jurisdiction?.country ? "needs_confirmation" : "manual_only", sourceContext: "Mapped from target_profile.jurisdiction." }));
  addQuestion(questions, createQuestion({ sectionKey: "company_jurisdiction_contacts", questionKey: "governing_law_and_venue", question: "Should governing law and courts/venue be selected now, bracketed, or left for local counsel?", answerType: "single_select", options: ["selected", "bracketed", "counsel_to_decide", "unknown"], vaultMatch: "none", assemblyPaths: ["assembly_handoff_intake.localisation.governing_law_instruction", "assembly_handoff_intake.localisation.courts_or_venue_instruction"], priority: "high", requiredFor: ["Localisation", "Counsel review"], prefillStatus: "needs_confirmation", sourceContext: "Diligence may detect jurisdiction signals but cannot choose counsel-specific venue language." }));
  addQuestion(questions, createQuestion({ sectionKey: "product_delivery_commercial_model", questionKey: "confirm_products_and_delivery", question: "Please confirm product names and delivery channels: web, app, mobile, API.", answerType: "object", vaultMatch: "perfect", vaultPaths: ["baseline.products", "baseline.delivery.web", "baseline.delivery.app", "baseline.delivery.mobile", "baseline.delivery.api"], priority: "critical", requiredFor: ["Document scope", "Service description", "API terms"], prefillStatus: asArray(packet.feature_map).length ? "needs_confirmation" : "manual_only", sourceContext: "Mapped from target_profile.product_baseline and target_feature_profile.feature_inventory." }));
  addQuestion(questions, createQuestion({ sectionKey: "product_delivery_commercial_model", questionKey: "confirm_market_and_revenue", question: "Please confirm whether the product is B2B, B2C, or hybrid, and the revenue model.", answerType: "object", vaultMatch: "perfect", vaultPaths: ["baseline.market", "baseline.revenue_model"], priority: "high", requiredFor: ["Terms", "Commercial model", "Liability route"], prefillStatus: "needs_confirmation", sourceContext: "Mapped from target_profile.business_model." }));
  addQuestion(questions, createQuestion({ sectionKey: "ai_functionality_autonomy_user_reliance", questionKey: "confirm_ai_archetypes", question: "Please confirm which AI functionality applies: actions, orchestration, content generation, document/data reading, conversational UI, decision support, security, optimization, or physical-world control.", answerType: "multi_select", options: ["doer", "orchestrator", "creator", "reader", "conversational_ui", "judge", "optimizer", "shield", "mover", "generalist"], vaultMatch: "perfect", vaultPaths: ["archetypes.is_doer", "archetypes.is_orchestrator", "archetypes.is_creator", "archetypes.is_reader", "archetypes.conversational_ui", "archetypes.is_judge", "archetypes.is_optimizer", "archetypes.is_shield", "archetypes.is_mover", "archetypes.is_generalist"], assemblyPaths: ["assembly_handoff_intake.document_routes.selected_documents"], priority: "critical", requiredFor: ["AI terms", "AUP", "Human review protocol"], prefillStatus: asArray(packet.feature_map).some((f) => asArray(f.archetype_codes).length) ? "needs_confirmation" : "manual_only", sourceContext: "Mapped from target_feature_profile.feature_inventory.archetype_codes." }));
  addQuestion(questions, createQuestion({ sectionKey: "data_users_regulated_surfaces", questionKey: "confirm_personal_and_sensitive_data", question: "Please confirm personal data, sensitive data, minors, employee, health, financial, and vulnerable-user surfaces.", answerType: "object", vaultMatch: "perfect", vaultPaths: ["compliance.processes_pii", "compliance.sens_health", "compliance.sens_fin", "compliance.sens_employment", "compliance.minors", "compliance.distress", "compliance.standard_adults"], assemblyPaths: ["assembly_handoff_intake.document_routes.selected_documents"], priority: "critical", requiredFor: ["Privacy Policy", "DPA", "DPIA memo", "Sensitive data clauses"], prefillStatus: dataFlows(packet).length ? "needs_confirmation" : "manual_only", sourceContext: "Mapped from data_provenance_profile." }));
  addQuestion(questions, createQuestion({ sectionKey: "technical_architecture_ai_supply_chain_integrations", questionKey: "ai_provider_stack", question: "Which AI/model providers are used?", answerType: "multi_select", options: AI_PROVIDER_OPTIONS, vaultMatch: "partial", vaultPaths: ["architecture.ai_provider_stack.providers", "architecture.sub_processors.openai", "architecture.sub_processors.anthropic", "architecture.sub_processors.google", "architecture.sub_processors.cohere", "architecture.sub_processors.mistral", "architecture.sub_processors.azure_openai", "architecture.sub_processors.aws_bedrock", "architecture.sub_processors.meta_llama", "architecture.sub_processors.deepseek", "architecture.sub_processors.xai", "architecture.sub_processors.other"], assemblyPaths: ["assembly_handoff_intake.document_routes.selected_documents", "assembly_handoff_intake.source_materials.existing_docs_urls"], priority: "critical", requiredFor: ["DPA", "Subprocessor Schedule", "AI Terms", "Privacy Policy"], prefillStatus: "needs_confirmation", sourceContext: "Mapped from target_feature_profile architecture hints and data_provenance_profile processor chain." }));
  addQuestion(questions, createQuestion({ sectionKey: "document_assembly_instructions", questionKey: "confirm_package_and_documents", question: "Please confirm which documents should be assembled first and whether existing public documents should be patched or replaced.", answerType: "multi_select", options: ["Terms", "Privacy Policy", "DPA", "AUP", "SLA", "AI Agent Terms", "IP/Output Terms", "Security Addendum", "Subprocessor Schedule", "Counsel Issue List"], vaultMatch: "partial", assemblyPaths: ["assembly_handoff_intake.document_routes.selected_documents", "assembly_handoff_intake.document_routes.existing_document_treatment"], priority: "critical", requiredFor: ["Document assembly"], prefillStatus: "needs_confirmation", sourceContext: "Mapped from legal_cartography and exposure_profile." }));
  addQuestion(questions, createQuestion({ sectionKey: "counsel_review_localisation", questionKey: "local_counsel_review", question: "Who will conduct local counsel review, and which jurisdiction-specific points should be prioritized?", answerType: "repeatable_table", vaultMatch: "none", assemblyPaths: ["assembly_handoff_intake.local_counsel_review.priority_points"], priority: "critical", requiredFor: ["Review-Ready disclaimer", "Final delivery"], prefillStatus: "manual_only", sourceContext: "Review-Ready Drafts require local counsel review before use." }));
  return questions;
}
